version: '3'
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        ports:
            - 5173:80              
        env_file:
            - .env
