export const menuItems = [
  {
    name: "Beranda",
    id: "beranda",
    icon: "/estore/icons/beranda-icon.svg",
    collapsed: false,
    role: ["admin"],
    link: "/",
  },
  {
    name: "Supplier",
    id: "supplier",
    icon: "/estore/icons/supplier-icon.svg",
    collapsed: false,
    role: ["admin"],
    link: "/supplier",
  },
  {
    name: "User Management",
    id: "user-management",
    icon: "/estore/icons/user-icon.svg",
    collapsed: false,
    role: ["admin"],
    link: "/user-management",
  },
  {
    name: "Master Data",
    id: "master-data",
    icon: "/estore/icons/database-icon.svg",
    collapsed: true,
    role: ["admin"],
    children: [
      {
        name: "Satuan Barang",
        link: "/master-data/satuan-barang",
        role: ["admin"],
      },
      {
        name: "Kategori Barang",
        link: "/master-data/kategori-barang",
        role: ["admin"],
      },
      {
        name: "Data Barang",
        link: "/master-data/data-barang",
        role: ["admin"],
      },
      // {
      //   name: "Ruang Kerja",
      //   link: "/master-data/ruang-kerja",
      //   role: ["admin"],
      // },
    ],
  },
  {
    name: "Barang Masuk",
    id: "barang-masuk",
    icon: "/estore/icons/barangmasuk-icon.svg",
    collapsed: false,
    role: ["admin"],
    link: "/barang-masuk",
  },
  {
    name: "Daftar Barang",
    id: "daftar-barang-user",
    icon: "/estore/icons/database-icon.svg",
    collapsed: false,
    role: ["user"],
    link: "/permintaan-barang-user",
  },
  {
    name: "Daftar Permintaan Barang",
    id: "minta-barang-user",
    icon: "/estore/icons/daftarpermintaan-icon.svg",
    collapsed: false,
    role: ["user"],
    link: "/list-permintaan-barang-user",
  },
  {
    name: "Daftar Permintaan Barang Oleh Admin",
    id: "minta-barang-user-admin",
    icon: "/estore/icons/daftarpermintaan-icon.svg",
    collapsed: false,
    role: ["admin"],
    link: "/list-permintaan-barang-user-admin",
  },
  {
    name: "Permintaan Barang",
    id: "minta-barang-admin",
    icon: "/estore/icons/permintaan-icon.svg",
    collapsed: false,
    role: ["admin"],
    link: "/permintaan-barang",
  },

  {
    name: "Laporan",
    id: "laporan",
    icon: "/estore/icons/paper-icon.svg",
    collapsed: true,
    role: ["admin"],
    children: [
      {
        name: "Laporan Barang Masuk",
        link: "/laporan-penerimaan",
        role: ["admin"],
      },
      {
        name: "Laporan Barang Keluar",
        link: "/laporan-pengeluaran",
        role: ["admin"],
      },
    ],
  },
];
